(define "veterancy_1"
;		{"lvl_1" 1
;		}
;		{"lvl_2" 2	
;		}
;		{"lvl_3" 4
;		}
;		{"lvl_4" 6
;		}
;		{"lvl_5" 8
;		}
)
(define "veterancy_crew"
;		{"crew_lvl_1" 3
;		}
;		{"crew_lvl_2" 8
;		}
;		{"crew_lvl_3" 12
;		}
;		{"crew_lvl_4" 15
;		}
;		{"crew_lvl_5" 20
;		}
)
(define "veterancy_crew_v"
;		{"crew_lvl_1" -1
;		}
;		{"crew_lvl_2" -1
;		}
;		{"crew_lvl_3" -1
;		}
;		{"crew_lvl_4" -1
;		}
;		{"crew_lvl_5" 0
;		}
)
(define "veterancy_specnaz"
;		{"specnaz_lvl_1" 2
;		}
;		{"specnaz_lvl_2" 3
;		}
;		{"specnaz_lvl_3" 5
;		}
;		{"specnaz_lvl_4" 7
;		}
;		{"specnaz_lvl_5" 9
;		}
)
