{units
(include "manpower_rus.inc")
(include "manpower_usa.inc")
(include "manpower_nato.inc")
(include "manpower_cn.inc")


;Land brigades	
	
;selectors

	{"vvs_mp_flag_1"					{tags "man_power vvs"}  {button "hqcar"} {group "hqcar4"} {icon 901} {charge 600} {cost 7000} {fore 1}}
	{"pvo_mp_flag_1"					{tags "man_power pvo"}  {button "hqcar"} {group "hqcar_pvo"} {icon 902} {charge 600} {cost 2700} {fore 1}}
	{"artbr_mp_flag_1"					{tags "man_power artbr"}  {button "hqcar"} {group "hqcar4"} {icon 903} {charge 600} {cost 7000} {fore 1}}
	{"vdv_mp_flag_1"					{tags "man_power mot"}  {button "hqcar"} {group "hqcar4"} {icon 904} {charge 600} {cost 10000} {fore 1}}
	{"mot_mp_flag_1"					{tags "man_power mot"}  {button "hqcar"} {group "hqcar4"} {icon 905} {charge 600} {cost 10000} {fore 1}}
	{"specbr_mp_flag_1"					{tags "man_power specbr"}  {button "hqcar"} {group "hqcar4"} {icon 906} {charge 600} {cost 10000} {fore 1}}
	
	{"usaf_mp_flag_1"					{tags "man_power usaf"}  {button "hqcar"} {group "hqcar4"} {icon 901} {charge 600} {cost 7000} {fore 1}}
	{"usa_aa_mp_flag_1"					{tags "man_power usa_aa"}  {button "hqcar"} {group "hqcar_pvo"} {icon 902} {charge 600} {cost 2700} {fore 1}}
	{"usart_mp_flag_1"					{tags "man_power usart"}  {button "hqcar"} {group "hqcar4"} {icon 903} {charge 600} {cost 7000} {fore 1}}
	{"usarmy_mp_flag_1"					{tags "man_power usarmy"}  {button "hqcar"} {group "hqcar4"} {icon 904} {charge 600} {cost 10000} {fore 1}}
	{"usmc_mp_flag_1"					{tags "man_power usmc"}  {button "hqcar"} {group "hqcar4"} {icon 905} {charge 600} {cost 10000} {fore 1}}
	{"idf_mp_flag_1"					{tags "man_power idf"}  {button "hqcar"} {group "hqcar4"} {icon 906} {charge 600} {cost 10000} {fore 1}}

;	{"nrf_mp_flag_1"					{tags "man_power nrf"}  {button "hqcar"} {group "hqcar4"} {icon 901} {charge 600} {cost 7000} {fore 1}}
;	{"nato_aa_mp_flag_1"				{tags "man_power nato_aa"}  {button "hqcar"} {group "hqcar_pvo"} {icon 902} {charge 600} {cost 2700} {fore 1}}
;	{"abn_mp_flag_1"					{tags "man_power abn"}  {button "hqcar"} {group "hqcar4"} {icon 903} {charge 600} {cost 7000} {fore 1}}
;	{"bund_mp_flag_1"					{tags "man_power bund"}  {button "hqcar"} {group "hqcar4"} {icon 904} {charge 600} {cost 10000} {fore 1}}
;	{"fra_mp_flag_1"					{tags "man_power fra"}  {button "hqcar"} {group "hqcar4"} {icon 905} {charge 600} {cost 10000} {fore 1}}
;	{"gb_mp_flag_1"						{tags "man_power gb"}  {button "hqcar"} {group "hqcar4"} {icon 906} {charge 600} {cost 10000} {fore 1}}

;	{"cnair_mp_flag_1"					{tags "man_power cnair"}  {button "hqcar"} {group "hqcar4"} {icon 901} {charge 600} {cost 7000} {fore 1}}
;	{"cnsam_mp_flag_1"					{tags "man_power cnsam"}  {button "hqcar"} {group "hqcar_pvo"} {icon 902} {charge 600} {cost 2700} {fore 1}}
;	{"cnart_mp_flag_1"					{tags "man_power cnart"}  {button "hqcar"} {group "hqcar4"} {icon 903} {charge 600} {cost 7000} {fore 1}}
;	{"cnheavy_mp_flag_1"				{tags "man_power cnheavy"}  {button "hqcar"} {group "hqcar4"} {icon 904} {charge 600} {cost 10000} {fore 1}}
;	{"cnmed_mp_flag_1"					{tags "man_power cnmed"}  {button "hqcar"} {group "hqcar4"} {icon 905} {charge 600} {cost 10000} {fore 1}}
;	{"iran_mp_flag_1"					{tags "man_power iran"}  {button "hqcar"} {group "hqcar4"} {icon 906} {charge 600} {cost 10000} {fore 1}}
}