;===============================Common=========================================== 
	{"bazookers(usa)"					{tags "man_power common"}  {button "1_common"} {group "eng"}		{icon 100} {charge 120} {cost 20} {fore 1}} 
	{"bazookers2(usa)"					{tags "man_power common"}  {button "1_common"} {group "jav"}		{icon 101} {charge 400} {cost 120} {fore 1.0}} 
	{"pzrk(usa)"						{tags "man_power common"}  {button "1_common"} {group "suppinf111"}	{icon 102} {charge 250} {cost 40} {fore 1}} 
	{"pzrk2_usa"						{tags "man_power common"}  {button "1_common"} {group "pzrk"}		{icon 103} {charge 500} {fore 1.0}}
	

	{"browning_m2hb_stan"				{tags "man_power common"}  {button "1_common"} {group "stan"}		{icon 104} {charge 300} {fore 1.0}}
	{"ptur_tow"							{tags "man_power common"}  {button "1_common"} {group "ptur"}		{icon 105} {charge 500} {fore 1.0}}
	{"mk19"								{tags "man_power common"}  {button "1_common"} {group "stan2"}		{icon 106} {charge 400} {fore 1.0}}
	{"m252"								{tags "man_power common"}  {button "1_common"} {group "stan2"}		{icon 107} {charge 600} {fore 1.0}}
	{"m120"								{tags "man_power common"}  {button "1_common"} {group "stan2"}		{icon 108} {charge 600} {fore 1.0}}
	
	{"smg(usa)"							{tags "man_power common"}  {button "1_common"} {group "inf_common"}	{icon 109} {charge 130} {cost 100} {fore 1.0}}
	{"m939i"							{tags "man_power common"}  {button "1_common"} {group "inf1"}		{icon 110} {charge 130} {fore 1.0}}
	{"mtvr_m2i"							{tags "man_power common"}  {button "1_common"} {group "inf1"}		{icon 111} {charge 420} {fore 1.0}}
	{"hmmwv_turret"						{tags "man_power common"}  {button "1_common"} {group "car2"}		{icon 112} {charge 240} {fore 1.0}}
	{"hmmwv_tow"						{tags "man_power common"}  {button "1_common"} {group "car_ptur"}	{icon 113} {charge 500} {fore 1.0}}
	{"m1097_avenger"					{tags "man_power common"}  {button "1_common"} {group "pvo1"}		{icon 114} {charge 240} {fore 1.0}}

;===============================Вспомогательные войска=========================================== supl
	{"m939_art"							{tags "man_power common"}  {button "2_supl"} {group "supply5"}		{icon 200} {charge 600} {fore 1.0}}
	{"m939_eng"							{tags "man_power common"}  {button "2_supl"} {group "supply6"}		{icon 201} {charge 240} {fore 1.0}}
	{"hemtt_refueller"					{tags "man_power common"}  {button "2_supl"} {group "fuel"}			{icon 202} {charge 240} {fore 1.0}}
	{"m939"								{tags "man_power common"}  {button "2_supl"} {group "truck"}		{icon 203} {charge 120} {fore 1.0}}

	{"tankman(usa)"						{tags "man_power common"}  {button "2_supl"} {group "supp"}			{icon 204} {charge 1} {cost 20} {fore 1.0}}
	{"vehicle_supporter(usa)"			{tags "man_power common"}  {button "2_supl"} {group "support"}		{icon 205} {charge 1} {cost 15} {fore 1.0}}
	{"operator_bpla(usa)"				{tags "man_power common"}  {button "2_supl"} {group "operator_bpla"} {icon 206} {charge 500} {cost 40} {fore 1.0}}
	{"pilot(usa)"						{tags "man_power common"}  {button "2_supl"} {group "supp"}			{icon 207} {charge 1} {cost 40} {fore 1.0}}
	{"switchblade300_catapult"			{tags "man_power common"}  {button "2_supl"} {group "kamikaze"}		{icon 208} {charge 600} {fore 1.0}}
	{"mstar_v6usa"						{tags "man_power common"}  {button "2_supl"} {group "mstar"}		{icon 209} {charge 1200} {fore -0.5}}
	
	{"uni_miners(usa)"					{tags "man_power common uni_miners"}  {button "2_supl"}				{icon 210} {charge 1} {cost 1} {fore 1.0}}
	{"engineers(usa)"					{tags "man_power common engineers"}  {button "2_supl"}				{icon 211} {charge 1} {cost 1} {fore 1.0}}
	{"corpsman(usa)"					{tags "man_power common corpsman"}  {button "2_supl"}				{icon 212} {charge 1} {cost 1} {fore 1.0}}
;===============================USAF===========================================
	{"a-10c_support_light"				{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "a10"}		{icon 301} {charge 260} {fore 0.0}}

	{"apache"							{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "heli"}		{icon 302} {charge 220} {fore 0.0}}
	{"apache_spike"						{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "heli_spike"} {icon 303} {charge 1200} {fore -0.5}}
;	{"a-10c_bomber"						{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "air_1s"}	{icon 304} {charge 600} {fore 0.0}}
	{"a-10c_at"							{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "air_1s"}	{icon 305} {charge 450} {fore -1.0}}
	{"a-10c_support"					{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "air_1s"}	{icon 306} {charge 450} {fore -1.0}}

	{"f-35c_stealthab"					{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "airb"}		{icon 307} {charge 450} {fore -0.8}}
	{"f-16c_support"					{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "air3"}		{icon 308} {charge 450} {fore -1.0}}
	{"f-16c_antirad_2"					{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "antirad"}	{icon 309} {charge 500} {fore 0.0}}
	{"f-35c_support"					{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "air_2s"}	{icon 310} {charge 500} {fore -1.3}}

	{"sso_usa"						{tags "man_power usaf"}  {button "3_usaf_hqcar"} {group "sso"}			{icon 311} {charge 500} {cost 40} {fore 0.8}}

;===============================US AA===========================================
	{"f-22_antiair"						{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "air"} {icon 401} {charge 450} {fore -1.8}}
	{"f-16c_aa"							{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "air"} {icon 402} {charge 400} {fore -1.5}}

	{"patriot_launcher_trailer"			{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "pvo45"} {icon 403} {charge 400} {fore -1.2}}
	{"patriot_radar_trailer"			{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "pvo46"} {icon 404} {charge 400} {fore -1.2}}
	{"nasams_ii_launcher_trailer"		{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "pvo2"} {icon 405} {charge 240} {fore -1.2}}
	{"hawk_rls_trailer"					{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "radar1"} {icon 406} {charge 300} {fore 0}}

	{"box_weapon_usa_excalibur"			{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "supply_spec"} {icon 407} {charge 1} {fore -1500}}
	{"box_weapon_usa_gmlrs_cl"			{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "supply_spec"} {icon 408} {charge 1} {fore -1800}}
	{"box_weapon_usa_gmlrs_aw"			{tags "man_power usa_aa"}  {button "4_usa_aa_hqcar"} {group "supply_spec"} {icon 409} {charge 1} {fore -1800}}
;===============================US artillery===========================================
	{"sappers(usa)"						{tags "man_power usart"}  {button "5_usart_hqcar"} {group "artinf1"} {icon 500} {charge 240} {cost 10} {fore 1.0}}
	{"spotters(usa)"					{tags "man_power usart"}  {button "5_usart_hqcar"} {group "artinf3"} {icon 501} {charge 300} {cost 50} {fore 1.0}}

	{"m119_trailer"						{tags "man_power usart"}  {button "5_usart_hqcar"} {group "art1"}	{icon 502} {charge 300} {fore 1.0}}
	{"m777a2_trailer"					{tags "man_power usart"}  {button "5_usart_hqcar"} {group "art2"}	{icon 503} {charge 360} {fore -1.0}}
	{"paladin"							{tags "man_power usart"}  {button "5_usart_hqcar"} {group "art3"}	{icon 504} {charge 300} {fore -2.0}}
	{"switchblade600_catapult"			{tags "man_power usart"}  {button "5_usart_hqcar"} {group "art4"}	{icon 505} {charge 450} {fore -1.0}}
	{"mrls"							    {tags "man_power usart"}  {button "5_usart_hqcar"} {group "him1"}	{icon 506} {charge 1400} {fore 0.0}}
	{"m142_himars"						{tags "man_power usart"}  {button "5_usart_hqcar"} {group "him1"}	{icon 507} {charge 1400} {fore 0.0}}
	{"mrls_atacms"						{tags "man_power usart"}  {button "5_usart_hqcar"} {group "art5"}	{icon 508} {charge 1800} {fore -0.1}}

;===============================US Army===========================================
	{"usara(usa)"						{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "inf"} {icon 600} {charge 120} {cost 85} {fore 1.0}}
	{"us_army_sniper(usa)"				{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "suppinf3"} {icon 601} {charge 480} {cost 50} {fore 1.0}}
	{"at_rifle(usa)"					{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "suppinf3"} {icon 602} {charge 480} {cost 50} {fore 1.0}}

	{"m939i_usarmy"						{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "first_inf1"} {icon 603} {charge 120} {fore 1.0}}
	{"m2a3"								{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp0"} {icon 604} {charge 300} {fore 1.0}}
	{"m2a3_brat"						{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp1"} {icon 605} {charge 300} {fore 1.0}}

	{"m1296"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp5"} {icon 606} {charge 300} {fore 1.0}}

	{"m2a3i"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp0"} {icon 607} {charge 300} {fore 1.0}}
	{"m2a3_brati"						{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp1"} {icon 608} {charge 300} {fore 1.0}}

	{"m1296i"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp5"} {icon 609} {charge 300} {fore 1.0}}
	{"m1126i"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp4"} {icon 610} {charge 140} {fore 1.0}}
	{"m1126jav"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp2"} {icon 611} {charge 300} {fore 1.0}}

	{"m1128"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "cartow"} {icon 612} {charge 450} {fore 1.0}}
	{"m1126_mk19"						{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp3"} {icon 613} {charge 600} {fore 1.0}}
	{"m-1129"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "spat"} {icon 614} {charge 500} {fore 1.0}}
	{"m1126_jav"						{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "bmp2"}	{icon 615} {charge 300} {fore 1.0}}
	{"m1134"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "stan2"} {icon 616} {charge 480} {fore 1.0}}

	{"m1a2tusk_2_m2_new"				{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "obt_army"} {icon 617} {charge 450} {fore 1.0}}
	{"m1a2_sep"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "obt_army"} {icon 618} {charge 450} {fore 1.0}}
	{"m1a2sep3"							{tags "man_power usarmy"}  {button "6_usarmy_hqcar"} {group "obt_army"} {icon 619} {charge 450} {fore 1.0}}	
	
;===============================USMC===========================================
	{"usmc(usa)"						{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "inf"}		{icon 701} {charge 120} {cost 85} {fore 1.0}}
	{"aavp7"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "aavp7"}	{icon 702} {charge 300} {fore 1.0}}
	{"lav25"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "lav25"}	{icon 703} {charge 300} {fore 1.0}}
	{"lav-ad"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "ad"}		{icon 704} {charge 600} {fore 1.0}}
	{"lav-atws"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "atws"}		{icon 705} {charge 400} {fore 1.0}}
	{"lav-mortarfr_trailer"				{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "mort"}		{icon 706} {charge 480} {fore 1.0}}
	
	{"m939i_usmc"						{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "inf1"}		{icon 707} {charge 600} {fore 1.0}}
	{"lav25i"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "lav25"} 	{icon 708} {charge 400} {fore 1.0}}
	{"aavp7i"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "aavp7"}	{icon 709} {charge 480} {fore 1.0}}
	{"uh1yi"							{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "uh1yi"}	{icon 710} {charge 500} {fore 0.36}}
	{"usmc_sturm(usa)"					{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "inf"}		{icon 701} {charge 120} {cost 45} {fore 1.0}}
	{"usmc_sniper(usa)"					{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "inf"}		{icon 701} {charge 480} {cost 45} {fore 1.0}}
	{"usmc_heavy_sniper(usa)"			{tags "man_power usmc"}  {button "7_usmc_hqcar"} {group "inf"}		{icon 701} {charge 480} {cost 50} {fore 1.0}}
;===========================Цахал==============================================
	{"idf(usa)"							{tags "man_power idf"}  {button "8_idf_hqcar"} {group "inf"}		{icon 800} {charge 120} {cost 85} {fore 1.0}}
	
	{"eitan_apc_ags"					{tags "man_power idf"}  {button "8_idf_hqcar"} {group "bmp3"}		{icon 801} {charge 600} {fore 1.0}}
	{"namer"							{tags "man_power idf"}  {button "8_idf_hqcar"} {group "bmp"}		{icon 802} {charge 600} {fore 1.0}}
	
	{"m113ai"							{tags "man_power idf"}  {button "8_idf_hqcar"} {group "inf2"}		{icon 803} {charge 240} {fore 1.0}}
	{"eitan_apc_mgi"					{tags "man_power idf"}  {button "8_idf_hqcar"} {group "bmp4"}		{icon 804} {charge 240} {fore 1.0}}
	{"nameri"							{tags "man_power idf"}  {button "8_idf_hqcar"} {group "inf22"}		{icon 805} {charge 600} {fore 1.0}}
	
	{"idf_at_rifle(usa)"				{tags "man_power idf"}  {button "8_idf_hqcar"} {group "suppinf3"}	{icon 806} {charge 480} {cost 50} {fore 1.0}}
	{"idf_sniper(usa)"					{tags "man_power idf"}  {button "8_idf_hqcar"} {group "suppinf3"}	{icon 807} {charge 480} {cost 30} {fore 1.0}}
	
	{"spike_stan_idf"					{tags "man_power idf"}  {button "8_idf_hqcar"} {group "spike"}		{icon 808} {charge 800} {fore 1.0}}
	
	{"magach7"							{tags "man_power idf"}  {button "8_idf_hqcar"} {group "arm2"}		{icon 809} {charge 390} {fore 1.0}}
	{"merkava_trophy"					{tags "man_power idf"}  {button "8_idf_hqcar"} {group "obt_idf"}	{icon 810} {charge 600} {fore 1.0}}

	
;===============================Спецюниты===========================================
	{"mq9"								{tags "man_power usaf"}  {button "special"} {group "extra1"}		{icon 2001} {charge 600} {fore -0.4}}
	{"f-22_fighter-bomber"				{tags "man_power usaf"}  {button "special"} {group "extra2"}		{icon 2002} {charge 450} {fore -1.2}}
	{"f-35c_strike"						{tags "man_power usaf"}  {button "special"} {group "extra3"}		{icon 2003} {charge 600} {fore -1.5}}

	{"m163"								{tags "man_power usa_aa"}  {button "special"} {group "extra1"}		{icon 2004} {charge 240} {fore 0.0}}
	{"e-2c_hawkeye"						{tags "man_power usa_aa"}  {button "special"} {group "extra2"}		{icon 2005} {charge 300} {fore 0.4}}
	{"f-35c_stealthaa"					{tags "man_power usa_aa"}  {button "special"} {group "extra3"}		{icon 2006} {charge 400} {fore -1.8}}

	{"mq9_recon"						{tags "man_power usart"}  {button "special"} {group "special1"}		{icon 2007} {charge 600} {fore 0.0}}	 
	;{"mrls_atacms_2"					{tags "man_power usart"}  {button "special"} {group "special2"}		{icon 2008} {charge 1800} {fore -0.1}}
	{"m777a1_trailer"					{tags "man_power usart"}  {button "special"} {group "special2"}		{icon 2009} {charge 460} {fore -1.0}}
	{"m142_himarser"					{tags "man_power usart"}  {button "special"} {group "special3"}		{icon 2010} {charge 1600} {fore -0.2}}	
	
	{"defend(usa)"						{tags "man_power usarmy"}  {button "special"} {group "extra10"}		{icon 2011} {charge 600} {cost 50} {fore 0.0}}
	{"shorad"							{tags "man_power usarmy"}  {button "special"} {group "extra11"}		{icon 2012} {charge 1200} {fore 0.0}}
	{"m1a2tusk_2_new"					{tags "man_power usarmy"}  {button "special"} {group "extra12"}		{icon 2013} {charge 1200} {fore 0.0}}
	
	{"usmcspec(usa)"					{tags "man_power usmc"}  {button "special"} {group "special1"}		{icon 2014} {charge 600} {cost 50} {fore 0.0}}
	{"m1a1_fep"							{tags "man_power usmc"}  {button "special"} {group "special2"}		{icon 2015} {charge 600} {fore -0.2}}
	{"ah1z"								{tags "man_power usmc"}  {button "special"} {group "special3"}		{icon 2016} {charge 1000} {fore 0.0}}
	
	{"idf_vdv(usa)"						{tags "man_power idf"}  {button "special"} {group "extra13"}		{icon 2017} {charge 600} {cost 50} {fore 0.0}}
	{"m163machbet"						{tags "man_power idf"}  {button "special"} {group "extra14"}		{icon 2018} {charge 300} {fore 0.0}}
	{"merkava_mk4"						{tags "man_power idf"}  {button "special"} {group "extra15"}		{icon 2019} {charge 1200} {fore 0.0}}
