;===============================общие войска=========================================== 
    {"bazookers2(rus)"					{tags "man_power common"}  {button "1_common"} {group "supp"} 		{icon 100} {charge 120} {fore 1} {cost 25}} 
    {"pzrk(rus)"						{tags "man_power common"}  {button "1_common"} {group "suppinf111"} {icon 101} {charge 250} {fore 1} {cost 40}} 
    {"pzrk2_rus"						{tags "man_power common"}  {button "1_common"} {group "pzrk"} 		{icon 102} {charge 500} {fore 0.8}} 
	
	{"kord_stan"						{tags "man_power common"}  {button "1_common"} {group "stan_mgun"}	{icon 103} {charge 300} {fore 1}} 
	{"ags30_stan"						{tags "man_power common"}  {button "1_common"} {group "stan1"}		{icon 104} {charge 400} {fore 1}} 
	{"2b11_trailer"						{tags "man_power common"}  {button "1_common"} {group "stan1"}		{icon 105} {charge 600} {fore 1}} 
	
	{"ptur_konkurs"						{tags "man_power common"}  {button "1_common"} {group "stan"}		{icon 106} {charge 500} {fore 1}} 
	{"metis_m"							{tags "man_power common"}  {button "1_common"} {group "ptursmall"}	{icon 107} {charge 400} {fore 1}} 
	{"kornet_base_stan"					{tags "man_power common"}  {button "1_common"} {group "stan3"}		{icon 108} {charge 800} {fore 1}} 
	
	{"shilka"							{tags "man_power common"}  {button "1_common"} {group "zpu"}		{icon 109} {charge 300} {fore 1}} 
	{"9k35_strela-10mn"					{tags "man_power common"}  {button "1_common"} {group "zrk"}		{icon 110} {charge 240} {fore 1}} 
	
	{"mso(rus)"							{tags "man_power common"}  {button "1_common"} {group "inf_common"}	{icon 111} {charge 94} {cost 70} {fore 1}}

	{"btr80_new"						{tags "man_power common"}  {button "1_common"} {group "bmp_common1"}{icon 112} {charge 420} {fore 1.0}}
	{"btr82a"							{tags "man_power common"}  {button "1_common"} {group "bmp_common2"} {icon 113} {charge 420} {fore 1.0}}
	{"ural375i"							{tags "man_power common"}  {button "1_common"} {group "inf"}		{icon 114} {charge 94} {fore 1.0}}
	{"btr80_newi"						{tags "man_power common"}  {button "1_common"} {group "inf"}		{icon 115} {charge 180} {fore 1.0}}
	{"btr82ai"							{tags "man_power common"}  {button "1_common"} {group "inf"}		{icon 116} {charge 420} {fore 1.0}}
	{"brdm2"							{tags "man_power common"}  {button "1_common"} {group "btr2"}		{icon 117} {charge 240} {fore 1.0}}

;===============================Вспомогательные войска=========================================== supl
	{"ural_art"							{tags "man_power common"}  {button "2_supl"} {group "supply6"}		{icon 201} {charge 600} {fore 1}}
	{"ural_eng"							{tags "man_power common"}  {button "2_supl"} {group "supply7"}		{icon 202} {charge 240} {fore 1}}
	{"ural-4320_fuel"					{tags "man_power common"}  {button "2_supl"} {group "fuel"}			{icon 203} {charge 240} {fore 1}}
	{"ural375"							{tags "man_power common"}  {button "2_supl"} {group "truck"}		{icon 204} {charge 120} {fore 1}}
	{"mtlb"								{tags "man_power common"}  {button "2_supl"} {group "btr1"}			{icon 205} {charge 250} {fore 1.0}}
	
	{"tankman(rus)"						{tags "man_power common tankman"}  {button "2_supl"} {group "eng"}	{icon 206} {charge 1} {cost 20} {fore 1}} 
	{"vehicle_supporter(rus)"			{tags "man_power common vs"}  {button "2_supl"} {group "support"}	{icon 207} {charge 30} {cost 25} {fore 1}} 
	{"pilot(rus)"						{tags "man_power common p"}  {button "2_supl"} {group "eng1"}		{icon 208} {charge 300} {cost 40} {fore 1}} 
	
	{"rus_las_designator"				{tags "man_power common"}  {button "2_supl"} {group "stan_mgun"}	{icon 209} {charge 300} {fore 1}} 
	{"eleron_complex"					{tags "man_power common"}  {button "2_supl"} {group "stane"}		{icon 210} {charge 500} {fore 1}} 
	{"ur_83p"							{tags "man_power common"}  {button "2_supl"} {group "stan_mgun"}	{icon 211} {charge 600} {fore 1}} 
	{"psnr5m"							{tags "man_power common"}  {button "2_supl"} {group "psnr"}			{icon 212} {charge 1200} {fore -0.5}} 
	
	{"uni_miners(rus)"					{tags "man_power common uni_miners"}  {button "2_supl"}				{icon 213} {charge 1} {cost 1} {fore 0.0}}
	{"engineers(rus)"					{tags "man_power common engineers"}  {button "2_supl"}				{icon 214} {charge 1} {cost 1} {fore 0.0}}
	{"corpsman(rus)"					{tags "man_power common corpsman"}  {button "2_supl"}				{icon 215} {charge 1} {cost 1} {fore 0.0}}
	
;===============================ВВС===========================================
	{"mi-24v_2"					    	{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "heli_lowc"}	{icon 301} {charge 300} {fore 0.36}}
	{"mi-24v_2"					    	{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "heli"}		{icon 302} {charge 240} {fore 0.36}}
	{"mi-24v_2"					    	{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "heli_at"}	{icon 303} {charge 350} {fore 0.36}}

	{"su-25sm_support_light"			{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "airsup"}		{icon 304} {charge 260} {fore 0.0}}
	{"su-34_antirad"					{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "antirad"}	{icon 305} {charge 500} {fore 0.0}}
	{"su-34_medbomber_light"			{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "air_2a"}		{icon 306} {charge 500} {fore -0.4}}
	{"su-34_accurate_2"					{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "air_2s"}		{icon 307} {charge 450} {fore -2.0}}
;	{"ka52_germes"						{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "helik"}		{icon 308} {charge 1800} {fore 0.0}}
	{"sso"							{tags "man_power vvs"}  {button "3_vvs_hqcar"} {group "artinf3"}		{icon 309} {charge 600} {cost 80} {fore 0.8}}
;===============================ПВО===========================================
	{"su-35_aa"							{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "air1"}		{icon 401} {charge 450} {fore -1.8}}
	{"mig-29s_aa_r77"					{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "air1"}		{icon 402} {charge 450} {fore -1.8}}

	{"tor_m2"							{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "pvo"}		{icon 403} {charge 450} {fore -1.8}}
	{"pantsir_s1"						{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "pvo1"}		{icon 404} {charge 450} {fore -1.8}}
	{"buk_m2"							{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "pvo17"}		{icon 405} {charge 450} {fore -1.8}}
	{"9s18_kupol"						{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "pvor"}		{icon 406} {charge 450} {fore -1.8}}
	{"p-37_trailer"						{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "radar"}		{icon 407} {charge 450} {fore -1.8}}

	{"box_weapon_rus_krasnopol"			{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "supplyart_spec"} {icon 408} {charge 1} {fore -1200}}
	{"box_weapon_rus_smerch_cl"			{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "supplyart_spec"} {icon 409} {charge 1} {fore -1200}}
	{"box_weapon_rus_smerch_tb"			{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "supplyart_spec_extra"} {icon 4010} {charge 1} {fore -1800}}
	{"box_weapon_rus_tornado_s_fg"		{tags "man_power pvo"}  {button "4_pvo_hqcar"} {group "supplyart_spec"} {icon 411} {charge 1} {fore -1200}}

;===============================Артиллеристы===========================================
	{"sappers(rus)"						{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "artinf1"} {icon 500} {charge 240} {cost 10} {fore 0.0}}
	{"spotters(rus)"					{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "artinf3"} {icon 501} {charge 200} {cost 20} {fore 0.0}}

	{"d30_trailer"					    {tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "stan1_1"} {icon 502} {charge 360} {fore 1.0}}
	{"msta_b_trailer"					{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "stan1_2"} {icon 503} {charge 360} {fore -1.0}}
	{"mstasm2"							{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "art1"}	{icon 504} {charge 300} {fore -2.0}}
	{"2s7m_malka"					    {tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "art1"}	{icon 505} {charge 300} {fore -2.0}}
	{"ural-4320_tornado_g"				{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "art2"}	{icon 506} {charge 300} {fore -2.0}}
	{"bm-30_tornado_s"					{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "art3"}	{icon 507} {charge 1400} {fore 0.0}}
	{"iskander"							{tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "brdtptur"} {icon 508} {charge 1800} {fore -0.1}}
	{"2c3_akaciya"					    {tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "brdtptur"} {icon 509} {charge 360} {fore -1.0}}
	{"eleron3sv"					    {tags "man_power artbr"}  {button "5_artbr_hqcar"} {group "brdtptur"} {icon 510} {charge 200} {fore 0.0}}
	
;===============================Мотострелки===========================================
	{"mot(rus)"							{tags "man_power mot"}  {button "6_mot_hqcar"} {group "inf"}		{icon 600} {charge 120} {cost 75} {fore 1.0}}
	
	{"bmp2_new"							{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp1"}		{icon 601} {charge 240} {fore 1.0}}
	;{"bmp2_kit_new"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp1"}		{icon 602} {charge 390} {fore 1.0}}
	{"bmp3_2022_sh1"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp2"}		{icon 603} {charge 390} {fore 1.0}}
	{"bmp2m_new"						{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp3"}		{icon 604} {charge 390} {fore -0.5}}
	
	{"ural375i_mot"						{tags "man_power mot"}  {button "6_mot_hqcar"} {group "first_inf1"} {icon 605} {charge 120} {fore 1.0}}
	{"bmp2_newi"						{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp1"}		{icon 606} {charge 240} {fore 1.0}}
	;{"bmp2_kit_newi"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp1"}		{icon 607} {charge 390} {fore 1.0}}
	{"bmp3_2022_sh1i"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp2"}		{icon 608} {charge 390} {fore 1.0}}
	{"bmp2m_newi"						{tags "man_power mot"}  {button "6_mot_hqcar"} {group "bmp3"}		{icon 609} {charge 390} {fore 0.0}}
	
	{"snipers2(rus)"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "snipers"}	{icon 610} {charge 480} {cost 50} {fore 1.0}}
	{"at_rifle(rus)"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "snipers"}	{icon 611} {charge 240} {cost 50} {fore 1.0}}
	
	{"vasilek_trailer"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "stan1"}		{icon 612} {charge 500} {fore 1.0}}
	
	{"9p149_shturm-s"					{tags "man_power mot"}  {button "6_mot_hqcar"} {group "brdtptur"}	{icon 613} {charge 600} {fore 1.0}}
	
	{"t72b"								{tags "man_power mot"}  {button "6_mot_hqcar"} {group "obt_mot1"}	{icon 614} {charge 450} {fore 1.0}}
	{"t72b3"							{tags "man_power mot"}  {button "6_mot_hqcar"} {group "obt_mot2"}	{icon 615} {charge 450} {fore 1.0}}
	{"t72b3_2017"						{tags "man_power mot"}  {button "6_mot_hqcar"} {group "obt_mot2"}	{icon 616} {charge 450} {fore 1.0}}

;===============================Морпехи===========================================
    {"mor(rus)"							{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "inf"}	{icon 700} {charge 120} {cost 75} {fore 1.0}}
    {"mor_flame(rus)"					{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "inf"}	{icon 701} {charge 160} {cost 110} {fore 1.0}}

	{"bmp2_kit_new"						{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "bmp2"}	{icon 702} {charge 240} {fore 1.0}}
	{"bmp3_2"						    {tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "bmp3"} {icon 703} {charge 390} {fore 1.0}}
	
	{"ural375i_mor"						{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "inf1"} {icon 704} {charge 120} {fore 1.0}}
	{"bmp2_kit_newi_mor"				{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "bmp2"} {icon 705} {charge 240} {fore 1.0}}
	{"bmp3_2i_mor"				     	{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "bmp3"} {icon 706} {charge 390} {fore 1.0}}
	
	{"snipers2_mor(rus)"				{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "snipers"} {icon 707} {charge 480} {cost 50} {fore 1.0}}
	{"at_rifle_mor(rus)"				{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "snipers"} {icon 708} {charge 240} {cost 50} {fore 1.0}}
	
	{"gaz_tigr"					        {tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "brdtptur"} {icon 709} {charge 400} {fore 1.0}}
	{"brdm2_atgm"				       	{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "brdtptur"} {icon 710} {charge 480} {fore 1.0}}
	{"kornet-d"					        {tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "brdtptur"} {icon 713} {charge 900} {fore 0.0}}

	{"t80bv_2"							{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "obt_mot1"} {icon 711} {charge 450} {fore 1.0}}
	{"t80bvm"							{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "obt_mot2"} {icon 712} {charge 450} {fore 1.0}}
	{"2b14_podnos"			        	{tags "man_power specbr"}  {button "7_specbr_hqcar"} {group "stan1"}{icon 714} {charge 500} {fore 1.0}}	
;===============================ВДВ===========================================
    {"stormtroopers2(rus)"				{tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "inf"}		{icon 800} {charge 120} {cost 75} {fore 1.0}}
	{"btr-d"						    {tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmp3vdv"}	{icon 801} {charge 120} {fore 1.0}}
	{"bmd2"						    	{tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmp1vdv"}	{icon 802} {charge 300} {fore 1.0}}
	{"bmd4m_sadovnitsa"					{tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmp2vdv"}	{icon 803} {charge 500} {fore 1.0}}

	{"btr-di"						    {tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmp3vdv"}	{icon 804} {charge 120} {fore 1.0}}
	{"bmd2i"						    {tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmp1vdv"}	{icon 805} {charge 300} {fore 1.0}}
	{"bmd4m_sadovnitsai"				{tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmp2vdv"}	{icon 806} {charge 500} {fore 1.0}}

	{"btr-rd"						    {tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "btrd"}		{icon 807} {charge 450} {fore 1.0}}
	{"2c9"								{tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "nona"}		{icon 808} {charge 600} {fore 1.0}}
	{"sprutsd"						    {tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "bmd"}		{icon 809} {charge 600} {fore 1.0}}
	{"mi8amtsh1_mgun"					{tags "man_power vdv"}  {button "8_vdv_hqcar"} {group "advinf3"}	{icon 810} {charge 240} {fore 1.0}}

;===============================Спецюниты===========================================
	{"shahed136_base"					{tags "man_power vvs"}  {button "special"} {group "extra01"}		{icon 2001} {charge 5} {fore -90.0}}
	{"su-34_kab"					    {tags "man_power vvs"}  {button "special"} {group "extra02"}		{icon 2002} {charge 600} {fore -0.6}}
	{"su-35_strike"					    {tags "man_power vvs"}  {button "special"} {group "extra03"}		{icon 2003} {charge 600} {fore -1.5}}

	{"buk_m1"							{tags "man_power pvo"}  {button "special"} {group "extra01"}		{icon 2004} {charge 600} {fore -1.2}}
	{"pantsir_s"					    {tags "man_power pvo"}  {button "special"} {group "extra02"}		{icon 2005} {charge 600} {fore -0.5}}
	{"su-50_aa"							{tags "man_power pvo"}  {button "special"} {group "extra03"}		{icon 2006} {charge 450} {fore -1.8}}

	{"2c3_akaciya"					    {tags "man_power artbr"}  {button "special"} {group "special4"}		{icon 2007} {charge 360} {fore -1.0}}
	{"bm-30_smerch"					    {tags "man_power artbr"}  {button "special"} {group "special2"}		{icon 2008} {charge 1500} {fore 0.0}}
	{"lancet3m_catapult_complex"		{tags "man_power artbr"}  {button "special"} {group "special5"}		{icon 2009} {charge 450} {fore -1.0}}	
	;{"tos-1a_solntsepek"				{tags "man_power artbr"}  {button "special"} {group "special3"}		{icon 2010} {charge 1800} {fore 0.0}}	
	;{"koalition"					    {tags "man_power artbr"}  {button "special"} {group "special1"}		{icon 2011} {charge 2400} {fore 0.0}}	
	
	{"elite(rus)"						{tags "man_power mot"}  {button "special"} {group "extra10"}		{icon 2012} {charge 600} {cost 50} {fore 0.0}}
	{"t-90a"							{tags "man_power mot"}  {button "special"} {group "extra11"}		{icon 2013} {charge 1200} {fore 0.0}}
	{"bmpt"								{tags "man_power mot"}  {button "special"} {group "extra12"}		{icon 2014} {charge 1500} {fore 0.0}}
	
	{"morspec(rus)"						{tags "man_power specbr"}  {button "special"} {group "extra10"}		{icon 2015} {charge 600} {cost 50} {fore 0.0}}
	{"t72b3_2017_2"						{tags "man_power specbr"}  {button "special"} {group "extra11"}		{icon 2016} {charge 1200} {fore 0.0}}
	{"ka52k"					      	{tags "man_power specbr"}  {button "special"} {group "extra12"}		{icon 2017} {charge 1500} {fore 0.0}}
	
	{"mi8amtsh1_mgnar"					{tags "man_power vdv"}  {button "special"} {group "extra7"}		{icon 2018} {charge 600} {fore 0}}
	{"kornet_stan"						{tags "man_power vdv"}  {button "special"} {group "extra8"}		{icon 2019} {charge 700} {fore 0}}
	{"mi-24vm"							{tags "man_power vdv"}  {button "special"} {group "extra9"}		{icon 2020} {charge 1000} {fore 0}}
