;===============================Common=========================================== 
{"hmmwv_m998" ("v_s" t(all) s(usa) sc(10) cw(0) cp(0) n(1))}
{"pzrk2_usa" ("v_s_inf" c1(hmmwv_m998) t(all) s(usa) sc(90) cw(0) cp(0) n(2) secondcrew(mp2/usa/pzrk_new:2 mp2/usa/pzrkhelp_new:2))}

{"browning_m2hb_stan" ("v_s" t(all) s(usa) sc(40) cw(10) cp(5) n(2))}
{"ptur_tow" ("v_s" t(all) s(usa) sc(60) cw(1) cp(5) n(2))}
{"mk19" ("v_s" t(all) s(usa) sc(130) cw(10) cp(15) n(2))}
{"m252" ("v_s" t(all) s(usa) sc(120) cw(1) cp(15) n(2))}
{"m120" ("v_s" t(all) s(usa) sc(160) cw(1) cp(15) n(3))}

{"m939" ("v_s" t(all) s(usa) sc(10) cw(0) cp(2) n(1))}
{"m939i" ("v_s_inf" c1(m939) t(all) s(usa) sc(105) cw(0) cp(2) n(1) secondcrew(mp2/usa/smg_newcom:1 mp2/usa/smg_new:2 mp2/usa/smg_gren:2 mp2/usa/smg_mgun:2 mp2/usa/smg_bazooker:2))}
{"mtvr_m2" ("v_s" t(all) s(usa) sc(10) cw(1) cp(2) n(2))}
{"mtvr_m2i" ("v_s_inf" c1(mtvr_m2) t(all) s(usa) sc(105) cw(0) cp(2) n(1) secondcrew(mp2/usa/smg_newcom:1 mp2/usa/vehicle_supporter:1 mp2/usa/smg_new:2 mp2/usa/smg_gren:2 mp2/usa/smg_mgun:2 mp2/usa/smg_bazooker:2))}
{"hmmwv_turret" ("v_s" t(all) s(usa) sc(40) cw(10) cp(10) n(5))}
{"hmmwv_tow" ("v_s" t(all) s(usa) sc(85) cw(0) cp(15) n(3))}

{"m1097_avenger" ("v_s" t(all) s(usa) sc(100) cw(0) cp(10) n(3))}
{"hawk_cwar" ("v_s" t(all) s(usa) sc(10) cw(0) cp(0) n(0))}
{"m1097_avenger_trailer" ("v_trailer" c1(m1097_avenger) c2(hawk_cwar) t(all) s(usa) sc(100) cw(5) cp(10) n(3) secondcrew())}

;===============================Вспомогательные войска=========================================== supl
{"m939_art" ("v_s" t(all) s(usa) sc(50) cw(0) cp(2) n(2))}
{"m939_eng" ("v_s" t(all) s(usa) sc(25) cw(0) cp(2) n(2))}
{"hemtt_refueller" ("v_s" t(all) s(usa) sc(15) cw(0) cp(2) n(2))}

{"switchblade300_catapult" ("v_custom" t(all) s(usa) sc(50) cw(0) cp(5) crew(mp2/usa/operator_kamikaze:1))}
{"mstar_v6usa" ("v_s" t(all) s(usa) sc(150) cw(0) cp(35) n(2))}

;===============================USAF===========================================
{"a-10c_support_light" ("v_p" t(all) s(usa) sc(330) cw(0) cp(25) n(1))}
{"apache" ("v_custom" t(all) s(usa) sc(220) cw(0) cp(25) crew(mp2/usa/vertpilot_apache:2))}
{"apache_spike" ("v_custom" t(all) s(usa) sc(450) cw(0) cp(25) crew(mp2/usa/vertpilot_apache:2))}

{"a-10c_bomber" ("v_p" t(all) s(usa) sc(450) cw(0) cp(75) n(1))}
{"a-10c_at" ("v_p" t(all) s(usa) sc(380) cw(0) cp(30) n(1))}
{"a-10c_support" ("v_p" t(all) s(usa) sc(380) cw(0) cp(30) n(1))}

{"f-35c_stealthab" ("v_p" t(all) s(usa) sc(300) cw(0) cp(45) n(1))}
{"f-16c_support" ("v_p" t(all) s(usa) sc(400) cw(0) cp(50) n(1))}
{"f-16c_antirad_2" ("v_p" t(all) s(usa) sc(170) cw(0) cp(30) n(1))}
{"f-35c_support" ("v_p" t(all) s(usa) sc(400) cw(0) cp(50) n(1))}

{"mh-6" ("v_heli" t(all) s(usa) sc(10) cw(0) cp(2) n(2))}
{"sso_usa" ("v_heli_inf" c1(mh-6) t(all) s(usa) sc(80) cw(0) cp(2) n(2) secondcrew(mp2/usa/delta_com_sso:1 mp2/usa/delta_marksman_sso:1 mp2/usa/delta_mgun_sso:1 mp2/usa/delta_smg_sso:1 mp2/usa/delta_smg2_sso:2))}
{"mq9" ("v_p" t(all) s(usa) sc(100) cw(0) cp(5) n(0))}
{"f-22_fighter-bomber" ("v_p" t(all) s(usa) sc(200) cw(0) cp(50) n(1))}
{"f-35c_strike" ("v_p" t(all) s(usa) sc(200) cw(0) cp(100) n(1))}

;===============================US AA===========================================
{"f-22_antiair" ("v_p" t(all) s(usa) sc(340) cw(0) cp(50) n(1))}
{"f-16c_aa" ("v_p" t(all) s(usa) sc(290) cw(0) cp(40) n(1))}

{"patriot_truck" ("v_s" t(all) s(usa) sc(10) cw(0) cp(2) n(2))}
{"patriot_launcher" ("v_s" t(all) s(usa) sc(90) cw(0) cp(25) n(0))}
{"patriot_radar" ("v_s" t(all) s(usa) sc(90) cw(0) cp(25) n(0))}
{"patriot_launcher_trailer" ("v_trailer" c1(patriot_truck) c2(patriot_launcher) t(all) s(usa) sc(100) cw(5) cp(25) n(2) secondcrew(mp2/usa/vehicle_supporter:0))}
{"patriot_radar_trailer" ("v_trailer" c1(patriot_truck) c2(patriot_radar) t(all) s(usa) sc(100) cw(5) cp(25) n(2) secondcrew(mp2/usa/vehicle_supporter:0))}

{"nasams_ii_launcher" ("v_s" t(all) s(usa) sc(100) cw(0) cp(2) n(2))}
{"hawk_cwar" ("v_s" t(all) s(usa) sc(50) cw(0) cp(20) n(0))}
{"nasams_ii_launcher_trailer" ("v_trailer" c1(nasams_ii_launcher) c2(hawk_cwar) t(all) s(usa) sc(150) cw(5) cp(20) n(2) secondcrew(mp2/usa/vehicle_supporter:0))}
{"hawk_rls" ("v_s" t(all) s(usa) sc(40) cw(0) cp(5) n(0))}
{"hawk_rls_trailer" ("v_trailer" c1(hmmwv_m998) c2(hawk_rls) t(all) s(usa) sc(50) cw(5) cp(5) n(2) secondcrew(mp2/usa/vehicle_supporter:0))}

{"box_weapon_usa_excalibur" ("v_s" t(all) s(usa) sc(50) cw(0) cp(2) n(2))}
{"box_weapon_usa_gmlrs_cl" ("v_s" t(all) s(usa) sc(100) cw(0) cp(2) n(2))}
{"box_weapon_usa_gmlrs_aw" ("v_s" t(all) s(usa) sc(100) cw(0) cp(2) n(2))}

{"m163" ("v_t" t(all) s(usa) sc(25) cw(0) cp(10) n(2))}
{"e-2c_hawkeye" ("v_p" t(all) s(usa) sc(50) cw(0) cp(20) n(5))}
{"f-35c_stealthaa" ("v_p" t(all) s(usa) sc(150) cw(0) cp(40) n(1))}
;===============================US artillery===========================================
{"hmmwv_m998_tent" ("v_s" t(all) s(usa) sc(10) cw(0) cp(2) n(2))}
{"m119" ("v_s" t(all) s(usa) sc(140) cw(0) cp(20) n(2))}
{"m119_trailer" ("v_trailer" c1(hmmwv_m998_tent) c2(m119) t(all) s(usa) sc(200) cw(5) cp(20) n(2) secondcrew(mp2/usa/vehicle_supporter:2))}

{"m777a1" ("v_s" t(all) s(usa) sc(200) cw(0) cp(15) n(3))}
{"m777a2" ("v_s" t(all) s(usa) sc(200) cw(0) cp(20) n(3))}
{"oshkosh_mtvr_cargo_mk25" ("v_s" t(all) s(usa) sc(10) cw(0) cp(2) n(2))}
{"m777a1_trailer" ("v_trailer" c1(oshkosh_mtvr_cargo_mk25) c2(m777a1) t(all) s(usa) sc(100) cw(5) cp(20) n(2) secondcrew(mp2/usa/vehicle_supporter:3))}
{"m777a2_trailer" ("v_trailer" c1(oshkosh_mtvr_cargo_mk25) c2(m777a2) t(all) s(usa) sc(400) cw(5) cp(20) n(2) secondcrew(mp2/usa/vehicle_supporter:3))}

{"paladin" ("v_t" t(all) s(usa) sc(600) cw(0) cp(60) n(4))}
{"switchblade600_catapult" ("v_custom" t(all) s(usa) sc(200) cw(0) cp(5) crew(mp2/usa/operator_kamikaze:1))}
{"mrls" ("v_t" t(all) s(usa) sc(1000) cw(0) cp(80) n(2))}
{"m142_himars" ("v_t" t(all) s(usa) sc(900) cw(0) cp(70) n(2))}
{"mrls_atacms" ("v_t" t(all) s(usa) sc(1000) cw(0) cp(80) n(2))}

{"mq9_recon" ("v_p" t(all) s(usa) sc(100) cw(0) cp(5) n(0))}
{"mrls_atacms_2" ("v_t" t(all) s(usa) sc(200) cw(0) cp(80) n(2))}
{"m142_himarser" ("v_s" t(all) s(usa) sc(500) cw(0) cp(75) n(2))}
;===============================US Army===========================================

{"m939i_usarmy" ("v_s_inf" c1(m939) t(all) s(usa) sc(100) cw(0) cp(15) n(1) secondcrew(mp2/usa/usara_com:1 mp2/usa/usara_smg:2 mp2/usa/usara_grenade:2 mp2/usa/usara_light_mgun:2 mp2/usa/usara_marksman:1 mp2/usa/usara_heavy_mgun:1))}
{"m2a3" ("v_t" t(all) s(usa) sc(90) cw(30) cp(25) n(3))}
{"m2a3_brat" ("v_t" t(all) s(usa) sc(135) cw(30) cp(25) n(3))}
{"m2a3i" ("v_t_inf" c1(m2a3) t(all) s(usa) sc(175) cw(0) cp(25) n(3) secondcrew(mp2/usa/usara_com:1 mp2/usa/usara_smg:2 mp2/usa/usara_grenade:1 mp2/usa/usara_light_mgun:1 mp2/usa/usara_marksman:1 mp2/usa/usara_heavy_mgun:1))}
{"m2a3_brati" ("v_t_inf" c1(m2a3_brat) t(all) s(usa) sc(205) cw(0) cp(25) n(3) secondcrew(mp2/usa/usara_com:1 mp2/usa/usara_smg:2 mp2/usa/usara_grenade:1 mp2/usa/usara_light_mgun:1 mp2/usa/usara_marksman:1 mp2/usa/usara_heavy_mgun:1))}

{"m1296" ("v_t" t(all) s(usa) sc(145) cw(30) cp(25) n(2))}

{"m1126" ("v_t" t(all) s(usa) sc(60) cw(30) cp(10) n(3))}
{"m1126_jav" ("v_t" t(all) s(usa) sc(160) cw(20) cp(20) n(3))}
{"m1126i" ("v_t_inf" c1(m1126) t(all) s(usa) sc(175) cw(0) cp(25) n(3) secondcrew(mp2/usa/usara_com:1 mp2/usa/usara_smg:2 mp2/usa/usara_grenade:2 mp2/usa/usara_light_mgun:2 mp2/usa/usara_marksman:1 mp2/usa/usara_heavy_mgun:1))}
{"m1126jav" ("v_t_inf" c1(m1126_jav) t(all) s(usa) sc(235) cw(0) cp(25) n(3) secondcrew(mp2/usa/usara_com:1 mp2/usa/usara_smg:2 mp2/usa/usara_grenade:2 mp2/usa/usara_light_mgun:2 mp2/usa/usara_marksman:1 mp2/usa/usara_heavy_mgun:1))}
{"m1296i" ("v_t_inf" c1(m1296) t(all) s(usa) sc(240) cw(0) cp(25) n(2) secondcrew(mp2/usa/usara_com:1 mp2/usa/usara_smg:2 mp2/usa/usara_grenade:2 mp2/usa/usara_light_mgun:2 mp2/usa/usara_marksman:1 mp2/usa/usara_heavy_mgun:1))}

{"m1128" ("v_t" t(all) s(usa) sc(170) cw(0) cp(20) n(3))}
{"m1126_mk19" ("v_t" t(all) s(usa) sc(145) cw(20) cp(30) n(3))}
{"m-1129" ("v_t" t(all) s(usa) sc(215) cw(0) cp(20) n(3))}
{"m1134" ("v_t" t(all) s(usa) sc(90) cw(0) cp(20) n(4))}

{"m1a2tusk_2_m2_new" ("v_t" t(all) s(usa) sc(290) cw(0) cp(60) n(4))}
{"m1a2_sep" ("v_t" t(all) s(usa) sc(320) cw(0) cp(60) n(4))}
{"m1a2sep3" ("v_t" t(all) s(usa) sc(370) cw(0) cp(70) n(4))}

{"shorad" ("v_t" t(all) s(usa) sc(300) cw(0) cp(40) n(4))}
{"m1a2tusk_2_new" ("v_t" t(all) s(usa) sc(350) cw(0) cp(65) n(4))}

;===============================USMC===========================================
{"aavp7" ("v_t" t(all) s(usa) sc(120) cw(0) cp(20) n(2))}
{"lav25" ("v_t" t(all) s(usa) sc(50) cw(0) cp(20) n(2))}
{"lav-ad" ("v_t" t(all) s(usa) sc(140) cw(0) cp(20) n(3))}
{"lav-atws" ("v_t" t(all) s(usa) sc(90) cw(0) cp(16) n(4))}
{"mortarfr" ("v_s" t(all) s(usa) sc(175) cw(0) cp(20) n(2))}
{"mortarfr_trailer" ("v_trailer" c1(hmmwv_m998_tent) c2(mortarfr) t(all) s(usa) sc(200) cw(5) cp(20) n(2) secondcrew(mp2/usa/vehicle_supporter:2))}

{"m1a1_fep" ("v_t" t(all) s(usa) sc(200) cw(0) cp(60) n(4))}
{"ah1z" ("v_heli" t(all) s(usa) sc(250) cw(0) cp(80) crew(mp2/usa/vertpilot_viper:2))}


{"m939i_usmc" ("v_s_inf" c1(m939) t(all) s(usa) sc(110) cw(0) cp(25) n(1) secondcrew(mp2/usa/usmc_com:1 mp2/usa/usmc_zamcom:5 mp2/usa/usmc_light_mgun:2 mp2/usa/usmc_smg:1 mp2/usa/usmc_marksman:1 mp2/usa/usmc_bazooker:1))}
{"lav25i" ("v_t_inf" c1(lav25) t(all) s(usa) sc(110) cw(0) cp(20) n(3) secondcrew(mp2/usa/usmc_light_mgun:1 mp2/usa/usmc_zamcom:1 mp2/usa/usmc_marksman:1 mp2/usa/usmc_smg:1 mp2/usa/usmc_bazooker:1))}
{"aavp7i" ("v_t_inf" c1(aavp7) t(all) s(usa) sc(225) cw(0) cp(20) n(3) secondcrew(mp2/usa/usmc_com:1 mp2/usa/usmc_zamcom:5 mp2/usa/usmc_light_mgun:2 mp2/usa/usmc_smg:1 mp2/usa/usmc_marksman:1 mp2/usa/usmc_bazooker:1))}
{"uh1y" ("v_heli" t(all) s(usa) sc(100) cw(0) cp(20) n(2))}
{"uh1yi" ("v_heli_inf" c1(uh1y) t(all) s(usa) sc(175) cw(0) cp(85) n(2) secondcrew(mp2/usa/usmc_com:1 mp2/usa/usmc_zamcom:1 mp2/usa/usmc_light_mgun:2 mp2/usa/usmc_smg:3 mp2/usa/usmc_marksman:1 mp2/usa/usmc_bazooker:1))}

;===========================Цахал==============================================
{"eitan_apc_ags" ("v_t_n" t(all) s(usa) na(idf) sc(145) cw(0) cp(30) n(3))}
{"namer" ("v_t_n" t(all) s(usa) na(idf) sc(180) cw(0) cp(30) n(3))}

{"m113a" ("v_t_n" t(all) s(usa) na(idf) sc(40) cw(0) cp(10) n(2))}
{"m113ai" ("v_t_inf_n" c1(m113a) t(all) s(usa) na(idf) sc(100) cw(0) cp(25) n(3) secondcrew(mp2/idf/idf_com:1 mp2/idf/idf_smg:1 mp2/idf/idf_hmgun:1 mp2/idf/idf_bazooker:1 mp2/idf/idf_marksman:1 mp2/idf/idf_bazooker2:1 mp2/idf/idf_smg2:1))}
{"eitan_apc_mg" ("v_t_n" t(all) s(usa) na(idf) sc(50) cw(0) cp(15) n(3))}
{"eitan_apc_mgi" ("v_t_inf_n" c1(eitan_apc_mg) t(all) s(usa) na(idf) sc(130) cw(0) cp(25) n(3) secondcrew(mp2/idf/idf_com:1 mp2/idf/idf_smg:1 mp2/idf/idf_hmgun:1 mp2/idf/idf_bazooker:1 mp2/idf/idf_marksman:1 mp2/idf/idf_bazooker2:1 mp2/idf/idf_smg2:1))}
{"nameri" ("v_t_inf_n" c1(namer) t(all) s(usa) na(idf) sc(260) cw(0) cp(25) n(3) secondcrew(mp2/idf/idf_com:1 mp2/idf/idf_smg:1 mp2/idf/idf_hmgun:1 mp2/idf/idf_bazooker:1 mp2/idf/idf_marksman:1 mp2/idf/idf_bazooker2:1 mp2/idf/idf_smg2:1))}

{"spike_stan_idf" ("v_s_n" t(all) s(usa) na(idf) sc(250) cw(0) cp(40) n(2))}

{"magach7" ("v_t_n" t(all) s(usa) na(idf) sc(180) cw(0) cp(40) n(4))}
{"merkava_trophy" ("v_t_n" t(all) s(usa) na(idf) sc(450) cw(0) cp(65) n(4))}

{"m163machbet" ("v_t_n" t(all) s(usa) na(idf) sc(50) cw(0) cp(15) n(3))}
{"merkava_mk4" ("v_t_n" t(all) s(usa) na(idf) sc(300) cw(0) cp(60) n(4))}


