{Extender "light"
;===============CtA
	{preset "lamp_spot"
		{light_fx 	"light_post_dir"}
		{light_bone "lamp_light_spot1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "lamp_spot_yellow"
		{light_fx 	"light_post_dir_yellow"}
		{light_bone "lamp_light_spot1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "lamp_point"
		{light_fx 	"light_post_plafond"}
		{light_bone "lamp_light_point1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	
	
;===========MoWAS
	{preset "lamp1"
		{light_fx 	"light_post_dir"}
		{light_bone "lamp_light_spot1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "lamp2"
		{light_fx 	"light_post_dir"}
		{light_bone "lamp_light_spot2"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass2"}
	}
	{preset "lamp3"
		{light_fx 	"light_post_dir"}
		{light_bone "lamp_light_spot3"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass3"}
	}
	{preset "lamp4"
		{light_fx 	"light_post_dir"}
		{light_bone "lamp_light_spot4"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass4"}
	}
	
	{preset "lamp1_point"
		{light_fx 	"light_post_plafond"}
		{light_bone "lamp_light_point1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "lamp2_point"
		{light_fx 	"light_post_plafond"}
		{light_bone "lamp_light_point2"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass2"}
	}
	{preset "lamp3_point"
		{light_fx 	"light_post_plafond"}
		{light_bone "lamp_light_point3"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass3"}
	}
	{preset "lamp4_point"
		{light_fx 	"light_post_plafond"}
		{light_bone "lamp_light_point4"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass4"}
	}
	
	
	
	{preset "light_wall1"
		{light_fx 	"light_wall_plafond"}
		{light_bone "lamp_light_point1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "light_lighthouse"
		{light_fx 	"light_lighthouse_dir"}
		{light_bone "lamp_light_spot1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
}